/* Shared learner runtime: the builder and standalone exports use this code. */
const LMS = (() => {
  const escape = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid = () => 'item-' + crypto.randomUUID();
  const mediaURL = value => {
    const s = String(value || '').trim();
    return /^(https?:\/\/[^\s<>"']+|(?:assets\/)?[a-zA-Z0-9_.-]+\.(?:mp4|webm|vtt))$/.test(s) ? s : '';
  };
  const fonts = {system:['System sans','system-ui, sans-serif'],humanist:['Humanist sans','Verdana, Geneva, sans-serif'],rounded:['Warm sans','Trebuchet MS, sans-serif'],serif:['Editorial serif','Georgia, serif'],book:['Book serif','Palatino Linotype, Book Antiqua, Palatino, serif'],classic:['Classic serif','Times New Roman, Times, serif'],mono:['Monospace','ui-monospace, SFMono-Regular, Consolas, monospace']};
  function applyTheme(root,s){for(const key of ['brand','background','surface','text','muted','border'])root.style.setProperty('--lms-'+key,s[key]);for(const [key,token,unit] of [['fontScale','scale',''],['spacing','space','px'],['contentWidth','content-width','px'],['radius','radius','px'],['lineHeight','leading','']])root.style.setProperty('--lms-'+token,s[key]+unit);root.style.setProperty('--lms-on-brand',lmsOnColor(s.brand));root.style.setProperty('--lms-body-font',fonts[s.font]?.[1]||fonts.system[1]);root.style.setProperty('--lms-heading-font',fonts[s.headingFont]?.[1]||fonts.system[1]);root.dataset.font=s.font;}
  const flatten = nodes => nodes.flatMap(n => n.type === 'section' ? flatten(n.children) : [n]);
  function validate(input) {
    if (!input || input.schemaVersion !== 1 || !Array.isArray(input.sections)) throw Error('Use a Design Lab LMS course.json file (schema 1).');
    const seen = new Set();
    const str = (v, max = 20000) => String(v ?? '').slice(0, max);
    const id = value => {const v = str(value,100); if(!/^[\w-]+$/.test(v)||['__proto__','constructor','prototype'].includes(v)||seen.has(v))throw Error('Course IDs must be unique.');seen.add(v);return v;};
    const quiz = n => ({id:id(n.id),type:'quiz',title:str(n.title,200)||'Quiz',questions:(Array.isArray(n.questions)?n.questions:[]).map(q=>({id:id(q.id),prompt:str(q.prompt,1000),options:(Array.isArray(q.options)?q.options:[]).map(v=>str(v,500)),answer:Number.isInteger(q.answer)?q.answer:0,explanation:str(q.explanation,2000)}))});
    const node = n => {
      if(!n||typeof n!=='object')throw Error('Invalid course item.');
      if(n.type==='quiz')return quiz(n);
      const base={id:id(n.id),type:n.type,title:str(n.title,200)||'Untitled'};
      if(n.type==='section'){if(!Array.isArray(n.children))throw Error('Section children must be a list.');return {...base,children:n.children.map(node)};}
      if(n.type==='slides')return {...base,slides:(Array.isArray(n.slides)?n.slides:[]).map(s=>({id:id(s.id),title:str(s.title,200),body:str(s.body)}))};
      if(n.type==='video')return {...base,url:mediaURL(n.url),captions:mediaURL(n.captions),transcript:str(n.transcript),description:str(n.description,2000)};
      throw Error('Unknown lesson type.');
    };
    const settings=input.settings||{},hex=(v,f)=>/^#[\da-f]{6}$/i.test(v)?v:f,number=(v,min,max,f)=>Number.isFinite(v)?Math.max(min,Math.min(max,v)):f;
    return {schemaVersion:1,id:id(input.id),title:str(input.title,200)||'Untitled course',description:str(input.description,4000),sections:input.sections.map(node),finalQuiz:quiz(input.finalQuiz||{id:uid(),title:'Final quiz',questions:[]}),settings:{passScore:Number.isFinite(settings.passScore)?Math.max(0,Math.min(100,Math.round(settings.passScore))):80,allowRetakes:settings.allowRetakes!==false,sequential:settings.sequential===true,requireLessons:settings.requireLessons!==false,brand:hex(settings.brand,'#8da6ff'),background:hex(settings.background,'#0c0e12'),surface:hex(settings.surface,'#14171d'),text:hex(settings.text,'#edf0f7'),muted:hex(settings.muted,'#a6afc0'),border:hex(settings.border,'#343b49'),fontScale:number(settings.fontScale,.8,1.4,1),spacing:number(settings.spacing,16,64,32),contentWidth:number(settings.contentWidth,640,1400,1000),radius:Number.isFinite(settings.radius)?Math.max(0,Math.min(32,settings.radius)):6,font:Object.hasOwn(fonts,settings.font)?settings.font:'system',headingFont:Object.hasOwn(fonts,settings.headingFont)?settings.headingFont:'system',lineHeight:number(settings.lineHeight,1.4,2,1.65)}};
  }
  const fingerprint = item => {let hash=0;for(const ch of JSON.stringify(item))hash=(Math.imul(31,hash)+ch.charCodeAt(0))|0;return String(hash);};
  function ready(course) {
    const lessons=flatten(course.sections),issues=[];
    if(!lessons.length)issues.push('Add at least one lesson.');
    for(const n of [...lessons,course.finalQuiz]){
      if(n.type==='slides'&&!n.slides.length)issues.push(n.title+': add a slide.');
      if(n.type==='video'&&!mediaURL(n.url))issues.push(n.title+': add a direct MP4/WebM video URL or local file.');
      if(n.type==='video'&&!n.transcript.trim())issues.push(n.title+': add a transcript or text alternative.');
      if(n.type==='quiz'){
        if(!n.questions.length)issues.push(n.title+': add a question.');
        for(const q of n.questions)if(!q.prompt.trim()||q.options.length<2||q.options.some(o=>!o.trim())||q.answer<0||q.answer>=q.options.length)issues.push(n.title+': finish each question, its choices and correct answer.');
      }
    }
    return [...new Set(issues)];
  }
  function mount(doc, raw, options={}) {
    const course=validate(raw),root=doc.querySelector('#lms-root');if(!root)return;
    const win=doc.defaultView,timerHost=options.timerHost||win,lessons=flatten(course.sections),all=[...lessons,course.finalQuiz],key='design-lab-lms-progress-'+course.id;let storage=options.storage;
    if(!storage)try{storage=win.localStorage;}catch{storage={getItem(){return null;},setItem(){throw Error('Storage unavailable');}};}
    let view=['settings','report'].includes(win.location.hash.slice(1))?win.location.hash.slice(1):'learn',active=lessons[0]?.id||course.finalQuiz.id,slide=0,message='',quizResult=null,disposed=false,lastTick=Date.now(),progress={name:'Learner',records:{},last:active},saveError=false;
    try{const stored=JSON.parse(storage.getItem(key)||'null');if(stored&&typeof stored==='object'){progress.name=String(stored.name||'Learner').slice(0,100);if(stored.records&&typeof stored.records==='object')for(const n of all){const r=stored.records[n.id];if(r?.fingerprint===fingerprint(n))progress.records[n.id]={fingerprint:r.fingerprint,completed:r.completed===true,notes:String(r.notes||'').slice(0,20000),seconds:Number.isFinite(r.seconds)?Math.max(0,r.seconds):0,slideSeen:Array.isArray(r.slideSeen)?r.slideSeen.filter(Number.isInteger):[],attempts:Array.isArray(r.attempts)?r.attempts.filter(a=>Number.isFinite(a.score)&&typeof a.at==='string').map(a=>({score:Math.max(0,Math.min(100,a.score)),at:a.at,passed:a.passed===true})):[]};}if(all.some(n=>n.id===stored.last))active=stored.last;}}catch{saveError=true;}
    const record=n=>progress.records[n.id]??=( {fingerprint:fingerprint(n),completed:false,seconds:0,slideSeen:[],attempts:[]} );
    const save=()=>{progress.last=active;try{storage.setItem(key,JSON.stringify(progress));}catch{saveError=true;}};
    const current=()=>all.find(n=>n.id===active);
    const completed=()=>lessons.filter(n=>record(n).completed).length;
    const locked=n=>n.id===course.finalQuiz.id?(course.settings.requireLessons&&completed()<lessons.length):course.settings.sequential&&lessons.slice(0,lessons.findIndex(x=>x.id===n.id)).some(x=>!record(x).completed);
    const finalPassed=()=>record(course.finalQuiz).completed;
    const percent=()=>Math.round((completed()+(finalPassed()?1:0))/Math.max(1,lessons.length+1)*100);
    const announce=text=>{root.querySelector('#lms-live').textContent=text;};
    const focusMain=()=>root.querySelector('#lms-heading')?.focus({preventScroll:true});
    const optionsHTML = n => n.questions.map((q,i)=>'<fieldset><legend>'+(i+1)+'. '+escape(q.prompt)+'</legend>'+q.options.map((choice,j)=>'<label class="lms-choice"><input type="radio" name="q-'+escape(q.id)+'" value="'+j+'" required> '+escape(choice)+'</label>').join('')+'</fieldset>').join('');
    const tree=nodes=>nodes.map(n=>n.type==='section'?'<li class="lms-outline-section"><details open><summary>'+escape(n.title)+'</summary><ul>'+tree(n.children)+'</ul></details></li>':'<li><button data-lms="open" data-id="'+n.id+'" '+(n.id===active&&view==='learn'?'aria-current="page"':'')+' '+(locked(n)?'disabled':'')+'><span>'+escape(n.title)+'</span><small>'+escape(n.type)+' · '+(record(n).completed?'Complete':locked(n)?'Locked':'Ready')+'</small></button></li>').join('');
    function lessonHTML(n){
      if(locked(n))return '<h2 id="lms-heading" tabindex="-1">'+escape(n.title)+'</h2><p>Complete the required lessons to unlock this quiz.</p>';
      const r=record(n),title='<p class="lms-eyebrow">'+(n.id===course.finalQuiz.id?'FINAL ASSESSMENT':escape(n.type))+'</p><h2 id="lms-heading" tabindex="-1">'+escape(n.title)+'</h2>';
      if(n.type==='slides'){
        const s=n.slides[slide];if(!s)return title+'<p>No slides yet. Add slides in the builder.</p>';
        if(!r.slideSeen.includes(slide)){r.slideSeen.push(slide);save();}
        const arrow=(direction,disabled)=>'<button class="lms-chevron lms-chevron-'+direction+'" data-lms="slide-'+direction+'" aria-label="'+(direction==='prev'?'Previous':'Next')+' slide" '+(disabled?'disabled':'')+'><svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="'+(direction==='prev'?'m15 5-7 7 7 7':'m9 5 7 7-7 7')+'"/></svg></button>';
        return '<article class="lms-slide lms-player-stage" aria-label="'+escape(n.title)+'"><div class="lms-slide-content"><h2 id="lms-heading" tabindex="-1">'+escape(s.title)+'</h2><div class="lms-prose">'+escape(s.body)+'</div></div>'+arrow('prev',slide===0)+arrow('next',slide>=n.slides.length-1)+'</article><section class="lms-lesson-details" aria-label="Lesson details"><div class="lms-player-toolbar"><p class="lms-muted">Slide '+(slide+1)+' of '+n.slides.length+'</p><button class="lms-primary" data-lms="complete" '+(r.slideSeen.length<n.slides.length?'disabled':'')+'>'+(r.completed?'Completed':'Mark lesson complete')+'</button></div><h3>'+escape(n.title)+'</h3><p class="lms-muted">Review every slide to enable completion.</p><label class="lms-notes-label">Lesson notes<textarea data-lms-notes="'+n.id+'" placeholder="Write your notes for this lesson…">'+escape(r.notes||'')+'</textarea></label></section>';
      }
      if(n.type==='video')return '<div class="lms-player-stage lms-video-stage">'+(n.url?'<video controls playsinline preload="metadata" aria-label="'+escape(n.title)+'"><source src="'+escape(options.resolveMedia?.(n.url)||n.url)+'">'+(n.captions?'<track kind="captions" src="'+escape(options.resolveMedia?.(n.captions)||n.captions)+'" srclang="en" label="English" default>':'')+'Your browser does not support this video.</video>':'<p>Add a direct video URL or upload a file in the builder.</p>')+'</div><section class="lms-lesson-details" aria-label="Lesson details"><div class="lms-player-toolbar"><p id="lms-video-status" role="status"></p><button class="lms-primary" data-lms="complete">'+(r.completed?'Completed':'Mark lesson complete')+'</button></div><h2 id="lms-heading" tabindex="-1">'+escape(n.title)+'</h2><p>'+escape(n.description)+'</p><details class="lms-transcript"><summary>Video transcript / text alternative</summary><div class="lms-prose">'+escape(n.transcript||'A transcript has not been provided yet.')+'</div></details><label class="lms-notes-label">Lesson notes<textarea data-lms-notes="'+n.id+'" placeholder="Write your notes for this lesson…">'+escape(r.notes||'')+'</textarea></label><p class="lms-muted">Completion is learner-confirmed; you can study the transcript instead of watching.</p></section>';
      const latest=r.attempts.at(-1),canAttempt=course.settings.allowRetakes||!r.attempts.length;
      return title+'<p>Passing score: '+course.settings.passScore+'%. '+(course.settings.allowRetakes?'Retakes allowed.':'One attempt per learner in this browser.')+'</p>'+(latest?'<p class="lms-result" role="status">Latest score: '+latest.score+'% · '+(latest.passed?'Passed':'Not passed')+' · Attempts: '+r.attempts.length+'</p>':'')+(quizResult?'<div class="lms-feedback">'+n.questions.map((q,i)=>'<p><strong>Question '+(i+1)+': '+(quizResult[i]===q.answer?'Correct':'Review')+'</strong> '+escape(q.explanation)+'</p>').join('')+'</div>':'')+(n.questions.length&&canAttempt?'<form id="lms-quiz">'+optionsHTML(n)+'<button class="lms-primary" type="submit">Submit '+(n.id===course.finalQuiz.id?'final quiz':'quiz')+'</button></form>':!n.questions.length?'<p>No questions yet. Add them in the builder.</p>':'<p>Retakes are disabled in course settings.</p>');
    }
    function reportsHTML(){const total=all.reduce((sum,n)=>sum+record(n).seconds,0);return '<p class="lms-eyebrow">BROWSER REPORT</p><h2 id="lms-heading" tabindex="-1">Learning report</h2><p>For '+escape(progress.name)+'. These records live in this browser; they are not combined with other learners.</p><div class="lms-metrics"><article><strong>'+percent()+'%</strong><span>Course progress</span></article><article><strong>'+completed()+'/'+lessons.length+'</strong><span>Lessons completed</span></article><article><strong>'+Math.round(total/60)+' min</strong><span>Active learning time</span></article><article><strong>'+(finalPassed()?'Passed':'Pending')+'</strong><span>Final assessment</span></article></div><div class="lms-table-scroll"><table><caption>Lesson completion and quiz attempts</caption><thead><tr><th scope="col">Lesson</th><th scope="col">Status</th><th scope="col">Time</th><th scope="col">Attempts</th><th scope="col">Best score</th></tr></thead><tbody>'+all.map(n=>{const r=record(n);return '<tr><th scope="row">'+escape(n.title)+'</th><td>'+(r.completed?'Complete':'In progress')+'</td><td>'+Math.round(r.seconds)+'s</td><td>'+r.attempts.length+'</td><td>'+(r.attempts.length?Math.max(...r.attempts.map(a=>a.score))+'%':'—')+'</td></tr>';}).join('')+'</tbody></table></div><button data-lms="csv">Download report CSV</button><p class="lms-muted">Time counts while Learn is open and the page is visible, and stops after 60 seconds without activity. Browser reports and quiz answers are editable on the client; use a backend for verified assessments.</p>';}
    function render(focus=false){
      const n=current();applyTheme(root,course.settings);root.classList.toggle('lms-settings-page',view==='settings');
      root.innerHTML='<a class="lms-skip" href="#lms-main">Skip to lesson</a><header class="lms-header"><div><p class="lms-eyebrow">LEARNING STUDIO</p><h1>'+escape(course.title)+'</h1></div><div class="lms-header-actions">'+(view==='settings'?'<button data-lms="view" data-view="learn">← Back to course</button>':'')+'<button class="lms-settings-button" data-lms="view" data-view="settings" aria-label="Settings" title="Settings"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="m10 3-1 3-3 1-2 3 2 2v3l3 1 1 3h4l1-3 3-1v-3l2-2-2-3-3-1-1-3z"/><circle cx="12" cy="11" r="3"/></svg></button><button data-lms="outline" aria-expanded="false" aria-controls="lms-outline">Course outline</button></div></header><nav class="lms-tabs" aria-label="Course views">'+[['learn','Course'],['report','Reports']].map(([v,label])=>'<button data-lms="view" data-view="'+v+'" aria-pressed="'+(view===v)+'">'+label+'</button>').join('')+'</nav><div class="lms-shell"><aside id="lms-outline" class="lms-outline"><label for="lms-progress">Course progress · '+percent()+'%</label><progress id="lms-progress" max="100" value="'+percent()+'"></progress><ul>'+tree(course.sections)+'<li><button data-lms="open" data-id="'+course.finalQuiz.id+'" '+(locked(course.finalQuiz)?'disabled':'')+' '+(active===course.finalQuiz.id&&view==='learn'?'aria-current="page"':'')+'><span>'+escape(course.finalQuiz.title)+'</span><small>Final quiz · '+(finalPassed()?'Passed':locked(course.finalQuiz)?'Locked':'Ready')+'</small></button></li></ul></aside><main id="lms-main" class="lms-main '+(view==='learn'&&['slides','video'].includes(n?.type)?'lms-media-page':'')+'" tabindex="-1">'+(view==='report'?reportsHTML():view==='settings'?'<p class="lms-eyebrow">YOUR PREFERENCES</p><h2 id="lms-heading" tabindex="-1">Learner settings</h2><label>Your display name<input id="lms-learner-name" maxlength="100" value="'+escape(progress.name)+'"></label><p>Saved progress is specific to this course and browser. Changed lesson content starts fresh progress for that lesson.</p><button data-lms="reset">Reset my progress</button><p class="lms-muted">Keyboard: Tab to controls, arrow keys to choose quiz answers. Video never autoplays. Your device’s reduced-motion preference is respected.</p>':n?lessonHTML(n):'<h2 id="lms-heading" tabindex="-1">Start building your course</h2>')+(message?'<p class="lms-result" role="status">'+escape(message)+'</p>':'')+(saveError?'<p role="status">Browser saving is unavailable. This session still works, but progress may not persist.</p>':'')+'</main></div><p id="lms-live" class="lms-sr" aria-live="polite" aria-atomic="true"></p>';
      root.querySelector('[data-lms-notes]')?.addEventListener('input',e=>{record(n).notes=e.target.value.slice(0,20000);save();});
      root.querySelector('#lms-learner-name')?.addEventListener('input',e=>{progress.name=e.target.value;save();});
      root.querySelector('#lms-quiz')?.addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const answers=n.questions.map(q=>Number(new win.FormData(e.target).get('q-'+q.id))),score=Math.round(answers.filter((a,i)=>a===n.questions[i].answer).length/n.questions.length*100),r=record(n);r.attempts.push({score,at:new Date().toISOString(),passed:score>=course.settings.passScore});r.completed=r.completed||score>=course.settings.passScore;quizResult=answers;message='Quiz submitted. '+score+'%. '+(score>=course.settings.passScore?'Passed.':'Review the feedback and try again if retakes are enabled.');save();render(true);});
      root.querySelector('video')?.addEventListener('error',()=>{root.querySelector('#lms-video-status').textContent='Video could not be loaded. Use the transcript or check the source URL.';});
      if(focus)focusMain();
    }
    function downloadCSV(){const cell=v=>'"'+String(v).replace(/^\s*[=+@-]/,"'$&").replaceAll('"','""')+'"',rows=[['Learner','Lesson','Type','Complete','Active seconds','Attempt','Score','Passed','Submitted at']];for(const n of all){const r=record(n);for(const a of r.attempts.length?r.attempts:[null])rows.push([progress.name,n.title,n.type,r.completed,Math.round(r.seconds),a?r.attempts.indexOf(a)+1:'',a?.score??'',a?.passed??'',a?.at??'']);}const blob=new win.Blob(['\ufeff'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=win.URL.createObjectURL(blob),link=doc.createElement('a');link.href=url;link.download='learning-report.csv';link.click();timerHost.setTimeout(()=>win.URL.revokeObjectURL(url),1000);announce('Report downloaded.');}
    root.addEventListener('click',e=>{const b=e.target.closest('[data-lms]');if(!b)return;const action=b.dataset.lms,n=current();lastActivity=Date.now();message='';if(action==='outline'){const open=root.querySelector('.lms-outline').classList.toggle('lms-outline-open');b.setAttribute('aria-expanded',String(open));return;}if(action==='view'){view=b.dataset.view;win.location.hash=view;quizResult=null;render(true);}if(action==='open'){const next=all.find(x=>x.id===b.dataset.id);if(!next||locked(next))return;active=next.id;slide=0;view='learn';win.location.hash='learn';quizResult=null;save();render(true);}if(action==='slide-prev'||action==='slide-next'){slide=Math.max(0,Math.min(n.slides.length-1,slide+(action==='slide-next'?1:-1)));render(true);announce('Slide '+(slide+1)+' of '+n.slides.length);}if(action==='complete'){record(n).completed=true;message='Lesson complete. Choose your next lesson in the outline.';save();render(true);}if(action==='csv')downloadCSV();if(action==='reset'){if(!win.confirm('Reset this learner’s progress and quiz attempts for this course?'))return;progress.records={};active=lessons[0]?.id||course.finalQuiz.id;slide=0;quizResult=null;message='Progress reset.';save();render(true);}});
    let lastActivity=Date.now();const activity=()=>lastActivity=Date.now();doc.addEventListener('keydown',activity);doc.addEventListener('pointerdown',activity);doc.addEventListener('scroll',activity,true);doc.addEventListener('pointermove',activity);
    const tick=()=>{const now=Date.now(),elapsed=Math.min(5,(now-lastTick)/1000);lastTick=now;if(!disposed&&view==='learn'&&!doc.hidden&&now-lastActivity<60000&&current()&&!locked(current())){record(current()).seconds+=elapsed;save();}};
    const hashChanged=()=>{const next=['settings','report'].includes(win.location.hash.slice(1))?win.location.hash.slice(1):'learn';if(next!==view){view=next;quizResult=null;render(true);}};win.addEventListener('hashchange',hashChanged);
    const timer=timerHost.setInterval(tick,1000);const dispose=()=>{tick();disposed=true;timerHost.clearInterval(timer);doc.removeEventListener('keydown',activity);doc.removeEventListener('pointerdown',activity);doc.removeEventListener('scroll',activity,true);doc.removeEventListener('pointermove',activity);win.removeEventListener('pagehide',dispose);win.removeEventListener('hashchange',hashChanged);save();};
    win.addEventListener('pagehide',dispose);render();return {updateTheme:settings=>Object.assign(course.settings,validate({...course,settings:{...course.settings,...settings}}).settings),dispose,report:()=>JSON.parse(JSON.stringify(progress)),course};
  }
  function lmsOnColor(hex){const rgb=hex.slice(1).match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4),l=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];return (l+.05)/.05>=1.05/(l+.05)?'#000000':'#ffffff';}
  return {fonts,applyTheme,escape,onColor:lmsOnColor,uid,mediaURL,flatten,validate,ready,mount};
})();
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',()=>{const data=document.querySelector('#lms-course-data');if(data&&document.querySelector('#lms-root'))try{LMS.mount(document,JSON.parse(data.textContent));}catch(e){document.querySelector('#lms-root').textContent='Course could not load: '+e.message;}});
